deplinenoise/tundra

scripts/tundra/tools/msvc-vscommon.lua

This is useful when you use Visual C++ with Windows XP targeting since you have to use an older SDK and 7.1 was the last version which had XP support.

Adds support for latest SDK that supports Windows XP

---

scripts/tundra/syntax/glob.lua

I noticed when building some filters that output of Glob/FGlob we returning paths with backslashes in some cases. The manual mentions that glob should return forward slashes, so maybe this is a regression in 2.0?
Not sure if this is the preferred solution for this problem, or if it should be addressed in the dirwalk code directly, but I thought I'd submit it anyway. :)

Normalizing glob output paths to have forward slashes as separators.

---

scripts/tundra/ide/msvc-common.lua
scripts/tundra/ide/msvc140.lua
scripts/tundra/tools/msvc-vs2015.lua
scripts/tundra/tools/msvc-vscommon.lua
scripts/tundra/tools/msvc-vswild.lua

This PR adds support for the VS2015 compiler and Windows 10 SDK.
By default the VS2015 targets the windows 8.1 SDK, as that mirrors MSBuild behaviour, but a specific Windows 10 SDK can be targeted by using `SdkVersion` (i.e. `SdkVersion = "v10.0.10166.0"`). To support this I have changed SdkVersion to use the actual SDK version instead of compiler version (i.e. `v7.0A`, `v8.1`). The old `SdkVersion` syntax is still supported and is distinguished by dropping the `v` prefix.

Support for VS2015 and Win10 SDK

---

scripts/tundra/ide/msvc-common.lua

Unfortunately this small mistake made in my previous pull request causes a lua error when using  `tundra2 -g`. I just noticed this mistake when starting a new project. Please excuse me for not testing my pull request thoroughly..

Fixed lua error introduced by pull request #252

---

examples/pch/src/pch.h
examples/pch/tundra.lua
examples/pch/units.lua
scripts/tundra/syntax/native.lua
scripts/tundra/tools/generic-cpp.lua

Previously (at least on Windows), one was unable to combine the use of
precompiled headers and globbing. This commit fixes two issues in that
regard:
1. Improve the accuracy of the check for "is the precompiled header
source file included in the list of sources".
2. Fix the check in generic_cpp_setup which determines whether this is THE
precompiled header source file, and if so, applies the special parameters
to it.
Also, added an example to the "pch" example, which demonstrates combining
precompiled headers with globbing. This is more of a test than an example,
and I'm in two minds about whether it's best to leave it in or remove it.

Fix precompiled headers in combination with globbing

---

scripts/tundra/tools/msvc-vscommon.lua

This small change adds support for using the new Visual C++ Build Tools
2015, which is a Microsoft-supplied installer that includes only the
compiler and SDK (but not Visual Studio).

Add support for Visual C++ Build Tools 2015

---

Makefile

Color output in `git branch` resulted in invalid filename
See issue #281 (https://github.com/deplinenoise/tundra/issues/281)

Added --no-color to git branch

---

scripts/tundra/ide/msvc-common.lua
scripts/tundra/ide/msvc140.lua
scripts/tundra/ide/msvc141.lua

- Consolidated meta project names
- Both meta projects are per solution, to allow multiple "tundra.lua" to target the same location.
- Added MsvcMetaProjectsDir hint to optionally put them in a separate location.
- Added Msvc.FilterRoot hint to be able to generate cleaner solutions when using absolute paths for Sources.
- Merge FilterRoots when combining projects using OutputProject.
- Allow "all" projects to specify the same OutputProject and have hints propagate from a best guess.

Added vs2017 solution generation

---

.gitignore
Makefile
src/BuildQueue.cpp
src/Driver.cpp
src/Driver.hpp
src/Main.cpp
src/Profiler.cpp
src/Profiler.hpp
src/ScanCache.cpp
vs2012/libtundra/libtundra.vcxproj
vs2012/libtundra/libtundra.vcxproj.filters

Optional `-p` / `--profile` flag dumps Google Chrome Tracing formatted profiling output to the given file.
Fixed VS2012 project too (`dlmalloc` files are gone now).

Profiler output option (in Chrome Tracing format)

---

src/DigestCache.cpp
src/DigestCache.hpp
src/Driver.cpp

We would try to clean up the digest cache not having initialized it.

Avoid crashing when there is no DAG data.

---

src/Driver.cpp

I noticed this on an x64 build on VS 2017 15.9.8
I also re-ordered the variables so that it's easier to spot an uninitialized one.

Fix uninitialized variable m_QuickstartGen

---

src/IncludeScanner.cpp

When using the generic (non-cpp) scanner to locate included files, if you don't have separators around your file path, there was an off-by-one bug which resulted in the final character of the path getting chopped off.

Fix generic scanner result length

---

scripts/tundra/ide/msvc-common.lua
scripts/tundra/ide/msvc142.lua
scripts/tundra/tools/msvc-vs2019.lua

One thing of interest is that when VS 2019 produces a solution (.sln)
file, it gives it this version heading:
Microsoft Visual Studio Solution File, Format Version 12.00
The other IDE generation files such as msvc141.lua emit higher numbers
than 12 (eg msvc141.lua emits 14.0). VS 2019 refuses to open .sln files
with numbers higher than 14.00, but it seems unlikely that the versions
between 12 to 14 make any difference. I've made the 2019 version 12.00,
for consistency with the native values produced by the IDE, but I'm not
sure if this is correct.

Add support for VS 2019

---

src/Config.hpp

Makes Tundra compile on AAarch64 (Apple Silicon) and passes all unit-tests

Added support for AAarch64 (Apple Silicon)

---

examples/ispc/tundra.lua
examples/ispc/units.lua
scripts/tundra/syntax/ispc.lua

This PR adds support to specify different targets when using ISPC like this
```lua
ISPC {
Pass = "IspcGen",
Source = "lanes.ispc",
Targets = "sse4,avx2"
},
```
When setting several targets to ISPC the compiler will generate one object file and one header for each target. The default function that one calls in this mode will do a run-time selection and call the appropriate one depending on instruction set the CPU supports. The user can chose to not use this function but instead calling `function_name_<target>` such as `foobar_avx2` and do the detection themselves.
Changes in this PR does a bunch of things
* First we need to tell Tundra about the output files the compiler generates which is the meat of this change.
* `Targets` is optional, so the user can chose to ignore it and use the old …

Added support for targets with ISPC

---

.github/workflows/build.yml
scripts/tundra/ide/msvc-common.lua
scripts/tundra/ide/msvc143.lua
scripts/tundra/tools/msvc-vs2022.lua
scripts/tundra/tools/msvc-vscommon-next.lua

Spent some time adding support for VS 2022, since it seemed pretty straightforward to get this up and running.
One thing of note, is that Microsoft have recently marked the `ToolsVersion` attribute as being obsolete.
> The MSBuild ToolsVersion attribute on the Project element in Visual Studio and MSBuild project files is considered obsolete in Visual Studio 2019 and later; you can safely delete it.
[ToolsVersion MSBuild Docs](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-toolset-toolsversion?view=vs-2022)
I've removed VS 2019 from the check that sets that attribute, as it seemed unnecessary, given what Microsoft has said.
`VCProjectVersion` seems to be completely undocumented, and I couldn't seem to find a VS 2019 or VS 2022 C++ project that has that element inside of it. …

Add support for VS 2022

---

src/Common.cpp

On my Linux system (ArchLinux) using `sysconf(_SC_NPROCESSORS_CONF);` will return 128 while my actual thread count is 32. This will cause Tundra to print an warning that number of threads gets clamped to 64, but after that will then crash.
This PR doesn't fix the underlying crash, but instead uses C++11 `std::thread::hardware_concurrency();` to get the number of hw threads in the system and this returns the correct value and now everything works as it should, but there is still another issue that makes tundra crash when thread count ends up being 128.
I know we use C++11 for Linux, but I'm unsure about the other targets. If that is true in all cases then it might be worth considering using this code path on all targets.

Fixed incorrect threads count on Linux

---

scripts/tundra/tools/msvc-clang.lua
scripts/tundra/tools/msvc-latest.lua

Now that Microsoft is actually distributing Clang as part of Visual Studio you can use clang instead of Visual C++ when you want to. There's more than one way to do this and I've just taken the easy path here to get something going.
In this first iteration, I've used the clang-cl and lld-link frontends because it allowed me to reuse the msvc base. This might not be desirable as the whole point of using clang is to gain access to clang features while this could be nice to have I'm wondering if people wouldn't rather see a more _native_ clang interface?
With that said, given the following `tundra.lua`:
```lua
Build {
Configs = {
{
Name = "win64-clang",
DefaultOnHost = "windows",
Tools = {
"msvc-clang"
}
}
},
Units = {
function()
Program {
Name = "test",
Sources = {
"test.cc"
}
} …
```

Added msvc-clang tools

---

src/BuildQueue.cpp
src/BuildQueue.hpp
src/Common.cpp
src/Exec.hpp
src/ExecUnix.cpp
src/ExecWin32.cpp
src/Hash.cpp
src/Main.cpp

Change static arrays to dynamically allocated arrays. I think we can afford two allocations per run of the tool.
The root cause was a bug where a copy of the configuration was taken before the clamp was applied.
However I'm still not sure why some Linux distributions lie and pretend to have 128 CPUs.
Fixes #346

Fixes for max CPU count of 64

---

scripts/tundra/boot.lua
scripts/tundra/ide/codelite.lua
scripts/tundra/ide/msvc-common.lua
scripts/tundra/ide/xcode3.lua
scripts/tundra/ide/xcode5.lua
scripts/tundra/ide/xcode7.lua
scripts/tundra/nodegen.lua

This PR forwards default nodes in IDE file generation code. As explained in this issue https://github.com/deplinenoise/tundra/issues/345
I cannot use utility function `make_lookup_table` because I'm building a lookup table from an _array of arrays_. I made sure though that it does this the same way it would do it if you flattened the array and then passed it to `make_lookup_table`.

Forward default nodes as lookup table in ide file generation
